image: openjdk:11

cache:
  paths:
    - .m2/repository/
    
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository/"
  DOCKER_HOST: tcp://localhost:2375

before_script:
   - apt-get install -qq xcftools

stages:
  - build tools
  - build javatask client
  - build plugins


build tools:
  stage: build tools
  script:
    - ./mvnw install -pl libs/org.ruminaq.tools
    
build javatask client:
  stage: build javatask client
  script:
    - ./mvnw install -pl libs/org.ruminaq.tasks.javatask.client

build plugins:
  stage: build plugins
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - MAVEN_OPTS=-Dmaven.repo.local=../../.m2/repository/ ./mvnw install --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
    - ./mvnw p2:site --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
    - ./mvnw jetty:run --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo &
    - sleep 60
    - ./mvnw install --toolchains=.gitlab-toolchains.xml spotbugs:spotbugs pmd:pmd checkstyle:checkstyle sonar:sonar
    
    
    