image: openjdk:11

cache:
  paths:
    - .m2/repository/
    
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository/"

stages:
  - build tools
  - build javatask client
  - build plugins


build tools:
  stage: build tools
  script:
    - ./mvnw install -pl libs/org.ruminaq.tools
    
build javatask client:
  stage: build javatask client
  script:
    - ./mvnw install -pl libs/org.ruminaq.tasks.javatask.client

build plugins:
  stage: build plugins
  script:
    - MAVEN_OPTS=-Dmaven.repo.local=../../.m2/repository/ ./mvnw install --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
    - ./mvnw p2:site --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
    - ./mvnw jetty:run --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo &
    - sleep 60
    - sudo ./mvnw install --toolchains=.gitlab-toolchains.xml spotbugs:spotbugs pmd:pmd checkstyle:checkstyle sonar:sonar
    
    
    