image: openjdk:11

cache:
  paths:
    - .m2/repository/

stages:
  - build tools
  - build javatask client


build tools:
  stage: build tools
  script:
    - ./mvnw install -pl libs/org.ruminaq.tools
    
build javatask client:
  stage: build javatask client
  script:
    - ./mvnw install -pl libs/org.ruminaq.tasks.javatask.client
