image: openjdk:11

cache:
  paths:
    - .m2/repository/
    
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository/"

stages:
  - build tools
  - build javatask client
  - generate thrift
  - build plugins

build tools:
  stage: build tools
  script:
    - ./mvnw install -pl libs/org.ruminaq.tools
    
build javatask client:
  stage: build javatask client
  script:
    - ./mvnw install -pl libs/org.ruminaq.tasks.javatask.client

generate thrift:
  stage: generate thrift
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd bundles/org.ruminaq.runner.thrift
    - mkdir -p target/generated-sources/thrift
    - docker run -v $(pwd):/data thrift thrift --gen java -r -out /data/target/generated-sources/thrift /data/src/main/thrift/ProcessSideServer.thrift
    - docker run -v $(pwd):/data thrift thrift --gen java -r -out /data/target/generated-sources/thrift /data/src/main/thrift/RemoteData.thrift
    - docker run -v $(pwd):/data thrift thrift --gen java -r -out /data/target/generated-sources/thrift /data/src/main/thrift/RunnerSideServer.thrift
    - ls target/generated-sources/thrift
    - cd ../..
  artifacts:
    paths:
    - bundles/org.ruminaq.runner.thrift/target

build plugins:
  stage: build plugins
  before_script:
    - apt-get update -qq
    - DEBIAN_FRONTEND=noninteractive apt-get install -qq keyboard-configuration
    - apt-get install -qq xvfb
    - apt-get install -qq xcftools
    - apt-get install -qq imagemagick
    - apt-get install -qq metacity
    - apt-get install at-spi2-core
    - apt-get -y install python3-pip python-dev
    - pip3 install -U setuptools
    - pip3 install -U virtualenvwrapper
    - apt-get install -qq texlive-latex-base
    - apt-get install -qq texlive-fonts-recommended
    - apt-get install -qq texlive-fonts-extra
    - apt-get install -qq texlive-latex-extra
    - apt-get install -qq r-base
    - wget "https://cran.r-project.org/src/contrib/R6_2.4.0.tar.gz"
    - R CMD INSTALL R6_2.4.0.tar.gz
    - ls bundles/org.ruminaq.runner.thrift/
    - ls bundles/org.ruminaq.runner.thrift/target/generated-sources/thrift
    - Xvfb :99 &
    - export DISPLAY=:99
    - metacity --sm-disable --replace 2> metacity.err &
  script:
    - MAVEN_OPTS=-Dmaven.repo.local=../../.m2/repository/ ./mvnw install --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
    - ./mvnw p2:site --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
    - ./mvnw jetty:run --toolchains=.gitlab-toolchains.xml -P init -pl releng/org.ruminaq.p2repo &
    - sleep 60
    - ./mvnw install --toolchains=.gitlab-toolchains.xml \
      '-Dsonar.host.url=https://sonarcloud.io' \
      -Dsonar.organization=systemincloud \
      -Dsonar.login=$SONAR_TOKEN \
      spotbugs:spotbugs pmd:pmd checkstyle:checkstyle sonar:sonar
  allow_failure: true
  after_script:
    - cat tests/org.ruminaq.eclipse.it.tests/target/work/data/.metadata/.log
    
    
    