language: java
dist: xenial
sudo: required

jdk:
  - openjdk10

services:
  - docker
  - xvfb
      
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq xcftools
  - sudo apt-get install -qq metacity
before_script:
  - metacity --sm-disable --replace 2> metacity.err &
  
script:
  - ./mvnw install -pl libs/org.ruminaq.tools
  - ./mvnw install -pl libs/org.ruminaq.tasks.javatask.client
  - ./mvnw install --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
  - ./mvnw p2:site --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
  - ./mvnw jetty:run --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo &
  - sleep 60
  - ./mvnw install --toolchains=.travis-toolchains.xml

cache:
  directories:
  - $HOME/.m2