language: java
dist: xenial
sudo: required
python:
  - "3.7"

jdk:
  - openjdk10

services:
  - docker
  - xvfb

addons:
  sonarcloud:
    organization: "systemincloud"
    token:
      secure: $SONAR_TOKEN

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq xcftools
  - sudo apt-get install -qq metacity
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - sudo apt-get install texlive-latex-base
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install texlive-fonts-extra
  - sudo apt-get install texlive-latex-extra
  - sudo apt install r-base
  - wget "https://cran.r-project.org/src/contrib/R6_2.4.0.tar.gz"
  - sudo R CMD INSTALL R6_2.4.0.tar.gz
  

install: skip

before_script:
  - metacity --sm-disable --replace 2> metacity.err &
  
script:
  - ./mvnw install -pl libs/org.ruminaq.tools
  - ./mvnw install -pl libs/org.ruminaq.tasks.javatask.client
  - ./mvnw install --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
  - ./mvnw p2:site --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
  - ./mvnw jetty:run --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo &
  - sleep 60
  - sudo ./mvnw install --toolchains=.travis-toolchains.xml spotbugs:spotbugs jxr:jxr pmd:pmd checkstyle:checkstyle sonar:sonar

cache:
  directories:
  - $HOME/.m2