language: java

jdk:
  - openjdk8

jobs:
  include:
    - stage: "Build JavaTask Client"
      install: skip
      script:
        - cd libs/org.ruminaq.tasks.javatask.client
        - mvn install
    - stage: unit tests
      script: "Running unit tests (2)"

#before_install:  
#  - cd releng/org.ruminaq.p2repo
#  - mvn p2:site
  
#script:
#  - mvn clean 

cache:
  directories:
  - $HOME/.m2
