language: java

jdk:
  - openjdk8

jobs:
  include:
    - stage: "Build JavaTask Client"
      install: skip
      script:
        - cd libs/org.ruminaq.tasks.javatask.client
        - mvn install
    - stage: "Build plugins"
      install: skip
      script:
        - cd releng/org.ruminaq.p2repo
        - mvn install --toolchains=../../.travis-toolchains.xml
        - mvn p2:site
        - sh -c "mvn jetty:run --toolchains=../../.travis-toolchains.xml &"
        - cd ../..
        - mvn validate
        
#before_install:  
#  - cd releng/org.ruminaq.p2repo
#  - mvn p2:site

cache:
  directories:
  - $HOME/.m2
