language: java

services:
  - docker

jdk:
  - openjdk10

jobs:
  include:
    - stage: "Build Tools"
      install: skip
      script:
        - ./mvnw install -pl libs/org.ruminaq.tools
    - stage: "Build JavaTask Client"
      install: skip
      script:
        - ./mvnw install -pl libs/org.ruminaq.tasks.javatask.client
    - stage: "Build plugins"
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq xcftools
      install: skip
      script:
        - ./mvnw install --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
        - ./mvnw p2:site --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo
        - ./mvnw jetty:run --toolchains=.travis-toolchains.xml -P init -pl releng/org.ruminaq.p2repo &
        - sleep 60
        - ./mvnw install --toolchains=.travis-toolchains.xml

cache:
  directories:
  - $HOME/.m2
