language: java

services:
  - docker

jdk:
  - openjdk8

jobs:
  include:
    - stage: "Build Tools"
      install: skip
      script:
        - ./mvnw install -pl libs/org.ruminaq.tools
    - stage: "Build JavaTask Client"
      install: skip
      script:
        - ./mvnw install -pl libs/org.ruminaq.tasks.javatask.client
    - stage: "Build plugins"
      install: skip
      script:
        - ./mvnw install --toolchains=../../.travis-toolchains.xml -pl releng/org.ruminaq.p2repo
        - ./mvnw p2:site -pl releng/org.ruminaq.p2repo
        - ./mvnw jetty:run --toolchains=../../.travis-toolchains.xml -pl releng/org.ruminaq.p2repo &
        - sleep 60
        - ./mvnw install --toolchains=.travis-toolchains.xml
        
#before_install:  
#  - cd releng/org.ruminaq.p2repo
#  - mvn p2:site

cache:
  directories:
  - $HOME/.m2
