<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagram" nsURI="http://ruminaq.org/diagram" nsPrefix="diagram">
  <eClassifiers xsi:type="ecore:EClass" name="RuminaqDiagram" eSuperTypes="platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Diagram">
    <eOperations name="getDiagramTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return CustomRuminaqDiagramImpl.DIAGRAM_TYPE_ID;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isVisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return true;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getGridUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return CustomRuminaqDiagramImpl.GRID_UNIT;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return CustomRuminaqDiagramImpl.getName(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isSnapToGrid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return CustomRuminaqDiagramImpl.isSnapToGrid();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return CustomRuminaqDiagramImpl.getGraphicsAlgorithm();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.graphiti.internal.IDiagramVersion.CURRENT;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainTask" eType="ecore:EClass ../../org.ruminaq.model.ruminaq/model/model.ecore#//MainTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuminaqShape" eSuperTypes="platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/ContainerShape">
    <eOperations name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return defaultActive;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isVisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return defaultVisible;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getParent" eType="#//RuminaqShape">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (RuminaqShape) getContainer();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultActive" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="true"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultVisible" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="true"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelObject" eType="ecore:EClass ../../org.ruminaq.model.ruminaq/model/model.ecore#//BaseElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortShape" abstract="true" eSuperTypes="#//LabeledRuminaqShape">
    <eOperations name="getWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return defaultWidth;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return defaultHeight;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return GraphicsAlgorithmFactory.INSTANCE.getGraphicsAlgorithm(this);"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultWidth" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        transient="true" defaultValueLiteral="30"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultHeight" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        transient="true" defaultValueLiteral="15"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPortShape" eSuperTypes="#//PortShape #//FlowSourceShape">
    <eOperations name="getAnchors">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return AnchorsFactory.INSTANCE.getAnchors(this);"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Anchor"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPortShape" eSuperTypes="#//PortShape #//FlowTargetShape">
    <eOperations name="getAnchors">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return AnchorsFactory.INSTANCE.getAnchors(this);"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Anchor"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelShape" eSuperTypes="#//RuminaqShape">
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return GraphicsAlgorithmFactory.INSTANCE.getGraphicsAlgorithm(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getGraphicsAlgorithm().getWidth();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getGraphicsAlgorithm().getHeight();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labeledShape" eType="#//LabeledRuminaqShape"
        eOpposite="#//LabeledRuminaqShape/label"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledRuminaqShape" eSuperTypes="#//RuminaqShape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//LabelShape"
        eOpposite="#//LabelShape/labeledShape"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskShape" eSuperTypes="#//LabeledRuminaqShape">
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return GraphicsAlgorithmFactory.INSTANCE.getGraphicsAlgorithm(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getChildren">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.emf.common.util.ECollections.asEList(java.util.stream.Stream.of(getInternalPort(), getTransientChildren()).flatMap(List::stream).collect(java.util.stream.Collectors.toList()));"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Shape"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalPort" upperBound="-1"
        eType="#//InternalPortShape" containment="true" eOpposite="#//InternalPortShape/task"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientChildren" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Shape"
        transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleConnectionShape" eSuperTypes="#//RuminaqConnection">
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return GraphicsAlgorithmFactory.INSTANCE.getGraphicsAlgorithm(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getConnectionDecorators">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return ConnectionDecoratorsFactory.INSTANCE.getConnectionDecorators(this);"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/ConnectionDecorator"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getStart" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Anchor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getSource().getAnchors().stream().findFirst().get();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getEnd" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Anchor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getTarget().getAnchors().stream().findFirst().get();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        unique="false" lowerBound="1" eType="#//FlowSourceShape" eOpposite="#//FlowSourceShape/outgoingConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        unique="false" lowerBound="1" eType="#//FlowTargetShape" eOpposite="#//FlowTargetShape/incomingConnections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuminaqConnection" eSuperTypes="platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/FreeFormConnection">
    <eOperations name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return true;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isVisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return true;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelObject" upperBound="-1"
        eType="ecore:EClass ../../org.ruminaq.model.ruminaq/model/model.ecore#//BaseElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleConnectionPointShape" eSuperTypes="#//RuminaqShape #//FlowSourceShape #//FlowTargetShape">
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return GraphicsAlgorithmFactory.INSTANCE.getGraphicsAlgorithm(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAnchors">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return AnchorsFactory.INSTANCE.getAnchors(this);"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Anchor"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getModelObject" eType="ecore:EClass ../../org.ruminaq.model.ruminaq/model/model.ecore#//BaseElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return ((RuminaqShapeImpl) getAnchors().get(0).getIncomingConnections().get(0).getStart().getParent()).getModelObject();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setCenteredX">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="setX(x - (getPointSize() >> 1));"/>
      </eAnnotations>
      <eParameters name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="setCenteredY">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="setY(y - (getPointSize() >> 1));"/>
      </eAnnotations>
      <eParameters name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointSize" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        transient="true" defaultValueLiteral="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowSourceShape" abstract="true" eSuperTypes="platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/AnchorContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" ordered="false"
        upperBound="-1" eType="#//SimpleConnectionShape" eOpposite="#//SimpleConnectionShape/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowTargetShape" abstract="true" eSuperTypes="platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/AnchorContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections" ordered="false"
        upperBound="-1" eType="#//SimpleConnectionShape" eOpposite="#//SimpleConnectionShape/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalPortShape" abstract="true" eSuperTypes="#//LabeledRuminaqShape">
    <eOperations name="getWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getGraphicsAlgorithm().getWidth();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getGraphicsAlgorithm().getHeight();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eType="#//TaskShape"
        eOpposite="#//TaskShape/internalPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalPortLabel" eType="#//InternalPortLabelShape"
        transient="true" eOpposite="#//InternalPortLabelShape/internalPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalInputPortShape" eSuperTypes="#//InternalPortShape #//FlowTargetShape">
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return GraphicsAlgorithmFactory.INSTANCE.getGraphicsAlgorithm(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAnchors">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return AnchorsFactory.INSTANCE.getAnchors(this);"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Anchor"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalOutputPortShape" eSuperTypes="#//InternalPortShape #//FlowSourceShape">
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return GraphicsAlgorithmFactory.INSTANCE.getGraphicsAlgorithm(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAnchors">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return AnchorsFactory.INSTANCE.getAnchors(this);"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Anchor"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalPortLabelShape" eSuperTypes="#//RuminaqShape">
    <eOperations name="getGraphicsAlgorithm" eType="ecore:EClass platform:/resource/org.eclipse.graphiti.mm/model/graphiti.ecore#//algorithms/GraphicsAlgorithm">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return GraphicsAlgorithmFactory.INSTANCE.getGraphicsAlgorithm(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getGraphicsAlgorithm().getX();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getGraphicsAlgorithm().getY();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalPort" eType="#//InternalPortShape"
        transient="true" eOpposite="#//InternalPortShape/internalPortLabel"/>
  </eClassifiers>
</ecore:EPackage>
