<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ruminaq" nsURI="http://ruminaq.org" nsPrefix="ruminaq">
  <eClassifiers xsi:type="ecore:EClass" name="BaseElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPort" upperBound="-1"
        eType="#//InputPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPort" upperBound="-1"
        eType="#//OutputPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" upperBound="-1" eType="#//Task"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atomic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//StringToStringMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preventLosts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalPort" abstract="true" eSuperTypes="#//BaseElement">
    <eOperations name="getTask" eType="#//Task">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (Task) eContainer();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        upperBound="-1" eType="#//DataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true" eSuperTypes="#//BaseElement">
    <eOperations name="getInputPort" eType="#//InternalInputPort">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getInputPort().stream().filter(ip -> ip.getId().equals(id)).findFirst().orElse(null);"/>
      </eAnnotations>
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getOutputPort" eType="#//InternalOutputPort">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getOutputPort().stream().filter(ip -> ip.getId().equals(id)).findFirst().orElse(null);"/>
      </eAnnotations>
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atomic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="looped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPort" upperBound="-1"
        eType="#//InternalOutputPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPort" upperBound="-1"
        eType="#//InternalInputPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyLocalUser" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//BaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalInputPort" eSuperTypes="#//InternalPort #//FlowTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="asynchronous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreLossyCast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="holdLast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultQueueSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultHoldLast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="debug" eType="#//debug/InternalInputPortDebug"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preventLostDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preventLost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalOutputPort" eSuperTypes="#//InternalPort #//FlowSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="synchronization" upperBound="-1"
        eType="#//Synchronization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resetPort" eType="#//InternalPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="debug" eType="#//debug/InternalOutputPortDebug"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowSource" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowTarget" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true" eSuperTypes="#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRef" lowerBound="1"
        eType="#//FlowSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRef" lowerBound="1"
        eType="#//FlowTarget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleConnection" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//FlowTarget #//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//FlowSource #//Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="asynchronous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="holdLast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedTask" eSuperTypes="#//UserDefinedTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationTask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedTask" abstract="true" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//StringToStringMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultParameters" upperBound="-1"
        eType="#//StringToStringMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToStringMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synchronization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="waitForPort" eType="#//InternalPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitForTicks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skipFirst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//InternalOutputPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skipLoop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DataType2" instanceClassName="dataType"/>
  <eSubpackages name="debug" nsURI="http://ruminaq.org/debug" nsPrefix="debug">
    <eClassifiers xsi:type="ecore:EClass" name="Debug" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="InternalPortDebug" abstract="true"
        eSuperTypes="#//debug/Debug"/>
    <eClassifiers xsi:type="ecore:EClass" name="InternalInputPortDebug" eSuperTypes="#//debug/InternalPortDebug"/>
    <eClassifiers xsi:type="ecore:EClass" name="InternalOutputPortDebug" eSuperTypes="#//debug/InternalPortDebug"/>
  </eSubpackages>
  <eSubpackages name="dt" nsURI="http://ruminaq.org/dt" nsPrefix="dt">
    <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="#//DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Bool" eSuperTypes="#//DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Numeric" abstract="true" eSuperTypes="#//DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Int32" eSuperTypes="#//dt/Numeric"/>
    <eClassifiers xsi:type="ecore:EClass" name="Int64" eSuperTypes="#//dt/Numeric"/>
    <eClassifiers xsi:type="ecore:EClass" name="Float64" eSuperTypes="#//dt/Numeric"/>
    <eClassifiers xsi:type="ecore:EClass" name="Float32" eSuperTypes="#//dt/Numeric"/>
    <eClassifiers xsi:type="ecore:EClass" name="Decimal" eSuperTypes="#//dt/Numeric"/>
    <eClassifiers xsi:type="ecore:EClass" name="Complex32" eSuperTypes="#//dt/Numeric"/>
    <eClassifiers xsi:type="ecore:EClass" name="Raw" eSuperTypes="#//DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Complex64" eSuperTypes="#//dt/Numeric"/>
  </eSubpackages>
</ecore:EPackage>
