<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="constant" nsURI="http://ruminaq.org/tasks/constant/1_0_0"
    nsPrefix="constant_1_0_0">
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="../../org.ruminaq.model.ruminaq/model/model.ecore#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="ecore:EClass ../../org.ruminaq.model.ruminaq/model/model.ecore#//DataType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
